name: corpus-builder

on:
  push:
    paths:
      - "corpus-core/**"
      - "corpus-builder/**"
      - "corpus-curation/**"
      - "corpus-format/**"
      - "corpus-sources/**"
      - "test-corpus/**"
      - "Makefile"
      - ".gitignore"
      - "archive.sh"
      - "concat_sibyl.sh"
      - ".github/workflows/corpus-builder.yml"
  pull_request:
    paths:
      - "corpus-core/**"
      - "corpus-builder/**"
      - "corpus-curation/**"
      - "corpus-format/**"
      - "corpus-sources/**"
      - "test-corpus/**"
      - "Makefile"
      - ".gitignore"
      - "archive.sh"
      - "concat_sibyl.sh"
      - ".github/workflows/corpus-builder.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install -e ./corpus-core -e './corpus-builder[dev]'
      - run: make check
